Tweak test
Signed-off-by: Morgan Douglas <mdouglas47@bloomberg.net>

diff --git a/tests/tran_foreign_key.test/runit b/tests/tran_foreign_key.test/runit
--- a/tests/tran_foreign_key.test/runit
+++ b/tests/tran_foreign_key.test/runit
@@ -6,53 +6,49 @@ dbname=$1
 echo db is $dbname 
 echo options $CDB2_OPTIONS
 
-(
-cdb2sql ${CDB2_OPTIONS} ${dbname} default - <<'EOF'
-drop table if exists t;
-drop table if exists q;
+set -e
 
-begin
-create table t {
-schema {
-    int a
+run_test() {
+    local test_input_file_name=$1
+
+    local test_name
+    test_name=$(echo ${test_input_file_name} | cut -d "." -f 1)
+
+    local exp_output_file_name=${test_name}.expected
+    local output_file_name=${test_name}.output
+
+    local cmd="cdb2sql -s -f ${test_input_file_name} ${CDB2_OPTIONS} ${dbname} default"
+    echo ${cmd} "> ${output_file_name}"
+    ${cmd} 2>&1 > ${output_file_name}
+
+    cmd="diff ${exp_output_file_name} ${output_file_name}"
+    echo ${cmd}
+    if ! ${cmd} > /dev/null; then
+        echo "failed ${test_name}"
+        echo "see diffs here: ${HOSTNAME}"
+        echo "> diff -u ${PWD}/{${exp_output_file_name},${output_file_name}}"
+        return 1
+    fi
 }
 
-keys {
-    "a" = a
+main() {
+    local failed_test=0
+
+    local test_input_files
+    test_input_files=$(find . -name 't[0-9][0-9].sql' -exec basename {} \;)
+
+    local test_input_file_name
+    for test_input_file_name in ${test_input_files}; do
+        echo "--- Running ${test_input_file_name} ---"
+        if run_test ${test_input_file_name}; then
+            echo "--- Passed ${test_input_file_name} ---"
+        else
+            echo "--- Failed ${test_input_file_name} ---"
+            failed_test=1
+        fi
+    done
+
+    return ${failed_test}
 }
 
-constraints {
-    "a" -> "q":"a" on delete cascade
-}
-} $$
-
-create table q {
-schema {
-    int a
-}
-
-keys {
-    "a" = a
-}
-} $$
-commit
-EOF
-
-echo insert into t fails
-cdb2sql ${CDB2_OPTIONS} ${dbname} "insert into t values(1)" ## fails
-echo insert into q
-cdb2sql ${CDB2_OPTIONS} ${dbname} "insert into q values(1)"
-echo insert into t now succeeds
-cdb2sql ${CDB2_OPTIONS} ${dbname} "insert into t values(1)" ## now succeeds
-echo "select * from t"
-cdb2sql ${CDB2_OPTIONS} ${dbname} "select * from t"         ## 1 
-echo "select * from t"
-cdb2sql ${CDB2_OPTIONS} ${dbname} "select * from q"         ## 1 
-echo "delete from q"
-cdb2sql ${CDB2_OPTIONS} ${dbname} "delete from q where 1"
-echo "select * from t"
-cdb2sql ${CDB2_OPTIONS} ${dbname} "select * from t"         ## empty 
-echo "select * from q"
-cdb2sql ${CDB2_OPTIONS} ${dbname} "select * from q"         ## empty?
-) > out 2>&1 
-exit 0
+main
