Update testcase
Signed-off-by: Morgan Douglas <mdouglas47@bloomberg.net>

diff --git a/tests/commit_lsn_map.test/runit b/tests/commit_lsn_map.test/runit
--- a/tests/commit_lsn_map.test/runit
+++ b/tests/commit_lsn_map.test/runit
@@ -24,6 +24,39 @@ cdb2sql ${CDB2_OPTIONS} $dbnm default 'select comdb2_dbname()'
 
 master=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'exec procedure sys.cmd.send("bdb cluster")' | grep MASTER | cut -f1 -d":" | xargs echo`
 
+kill_restart_cluster()
+{
+    for node in $CLUSTER ; do
+        echo "killrestart nodes $node"
+        kill_restart_node $node $kill_wait_time &
+    done
+    sleep $kill_wait_time
+    # select 1 all nodes
+    for node in $CLUSTER ; do
+        out=$(cdb2sql ${CDB2_OPTIONS} --tabs --host $node $DBNAME  'select 1' 2>/dev/null)
+        # wait until we can query it
+        echo "$DBNAME: waiting until ready"
+        while [[ "$out" != "1" ]]; do
+            sleep $kill_wait_time
+            out=$(cdb2sql ${CDB2_OPTIONS} --tabs --host $node $DBNAME  'select 1' 2>/dev/null)
+        done
+    done
+}
+
+function failif
+{
+	if [[ $1 -ne 0 ]]; then
+		exit 1
+	fi
+}
+
+function bounce {
+	if [[ -n "$CLUSTER" ]] ; then
+		kill_restart_cluster 
+	else
+		kill_restart_node $(hostname) $kill_wait_time
+	fi
+}
 
 # Count the number of logs that are ready to archive
 function count_archive
@@ -31,6 +64,48 @@ function count_archive
     typeset dbnm=$1
     cdb2sql --tabs ${CDB2_OPTIONS} --host $master $dbnm 'exec procedure sys.cmd.send("bdb log_archive")' | egrep 'log.00000' | wc -l
 }
+
+######################
+# TEST 1 - child txns
+######################
+
+function setup
+{
+	cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t(int utxnid, int childutxnid)'
+	cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table q(int utxnid, int childutxnid)'
+	cdb2sql ${CDB2_OPTIONS} $dbnm default 'insert into t select utxnid, childutxnid from comdb2_transaction_logs where childutxnid is not null'
+	cdb2sql ${CDB2_OPTIONS} $dbnm default 'insert into q select * from t where not exists (select * from comdb2_transaction_commit where t.childutxnid=comdb2_transaction_commit.utxnid'
+}
+
+function verify_child_commit_lsn_is_parent_commit_lsn
+{
+
+	res=$(cdb2sql ${CDB2_OPTIONS} $dbnm default 'select COUNT(*) from comdb2_transaction_commit parent, comdb2_transaction_commit child, t logs where logs.utxnid=parent.utxnid and logs.childutxnid=child.utxnid and (parent.commitlsnfile!=child.commitlsnfile or parent.commitlsnoffset!=child.commitlsnoffset)')
+	numinvalidchildren=$(echo $res | grep -oP "[0-9]+\)$")
+	echo "numinvalidchildren $numinvalidchildren"
+	failif numinvalidchildren
+}
+
+setup
+verify_child_commit_lsn_is_parent_commit_lsn
+
+bounce
+
+res=$(cdb2sql ${CDB2_OPTIONS} $dbnm default 'select COUNT(*) from comdb2_transaction_commit commits, t logs where commits.utxnid=t.childutxnid')
+numrecoveredchildren=$(echo $res | grep -oP "[0-9]+\)$")
+echo "numrecoveredchildren $numrecoveredchildren"
+
+verify_child_commit_lsn_is_parent_commit_lsn
+
+#master_swing
+
+#setup
+#verify_child_commit_lsn_is_parent_commit_lsn
+#teardown
+
+#####################
+# TEST 2 - log deletion
+#####################
 
 
 # Let the test
@@ -126,4 +201,6 @@ if ((numfilesinmap - numremainingfiles < seencountsave)); then
     exit 1
 fi
 
-echo "Logfiles deleted!  Success!"
+
+
+
